### ISSUE TITLE
Shimming more methods?

### ISSUE THREAD

**Issue by hgl** [WebReflection/dom4#11]
Are you interested in shimming more methods, some of which could benefit the libaray itself directly:

- if the reference child passing to `insertBefore()` is falsy, use `appendChild()` instead. (doesn't work for ie, not sure which versions)
- make the `useCapture` argument optional for `addEventListener()` (doesn't work for firefox before v6 according to mdn, also ie before v9)

I swear I've encountered more like these, but somehow these are only ones I can remember right now.

**Comment by WebReflection** [comment]
IIRC are **not** DOM4 related changes/concerns so probably out of this library scope.
Although, if you'll push a PR with tests in too I might consider it.
