### ISSUE TITLE
IE9 - SCRIPT5022 SyntaxError 

### ISSUE THREAD

**Issue by zabojad** [WebReflection/dom4#12]
Just tryied this lib on IE9 and I get: SCRIPT5022 SyntaxError on line 2088 of dom4.js

How can I know the cause of this error ?

Thanks

**Comment by WebReflection** [comment]
which IE9 ? Mobile, Desktop 32 or Desktop 64 bits ? Is it the proper one or it's an emulated one ? Thanks for any sort of extra detail

**Comment by WebReflection** [comment]
also ... is this page green ? http://webreflection.github.io/dom4/test/

**Comment by zabojad** [comment]
Hi,

It's the IE9 on windows 7 from browserstack.com...

I don't think 32 bits or 64 bits makes any difference at that level...

> also ... is this page green ? http://webreflection.github.io/dom4/test/

Yes it is !

**Comment by WebReflection** [comment]
it does, there are quirks behvior so yes, it's important, I wouldn't have asked otherwise ;-)

So, all tests passes, how can I help you? What are you trying to do? Which code does what in your application? Which part fails? ... etc etc ...
