### ISSUE TITLE
bower main

### ISSUE THREAD

**Issue by TrySound** [WebReflection/dom4#14]
bower.main field must contain non-minified version

**Comment by WebReflection** [comment]
... sorry, what? there's no bower main, only package.json main + why is that?

**Comment by TrySound** [comment]
@WebReflection  bower.json main field
https://github.com/bower/bower.json-spec#main

**Comment by TrySound** [comment]
@WebReflection I use [main-bower-files](https://github.com/ck86/main-bower-files) for building apps with bower.

**Comment by WebReflection** [comment]
I see ... OK, `1.3.2` points to the `.max` file. Does that work?

**Comment by TrySound** [comment]
@WebReflection  Yes. Thanks you!

**Comment by jpdevries** [comment]
i'm working on adding `dom4` to a project and I musk ask, why omit the `./src` directory?
https://github.com/WebReflection/dom4/blob/master/bower.json#L10

It would be nice to have that there to copy from

**Comment by WebReflection** [comment]
it's redundant. That file is used to generate all files in the `./build` folder where you will fine the right file with copyrights and eventually AMD or CommonJS style wrap

**Comment by WebReflection** [comment]
actually, that's how it is usually, here you just have the full dom.max file since there's nothing exported, but again that is the file I want to distribute, with the right info and license included.

Regards
