### ISSUE TITLE
shadowRoot

### ISSUE THREAD

**Issue by cbas** [WebReflection/dom4#15]
Are these methods meant to work on shadow roots? It would be nice to traverse the DOM this way. Currently this doesn't seem to work.

```js
this.createShadowRoot().query // undefined
```

**Comment by WebReflection** [comment]
the `ShadowRoot` prototype is not involved. Can you please verify query and queryAll should work there too? I think the answer would be logically yes but worth double checking. Thanks

**Comment by cbas** [comment]
I'm new to these specs so please forgive me if I make wrong assumptions.
https://dom.spec.whatwg.org/#parentnode
```idl
interface ParentNode {
  ...
  [Unscopeable] Element? query(DOMString relativeSelectors);
  [NewObject, Unscopeable] Elements queryAll(DOMString relativeSelectors);
  ...
};
...
DocumentFragment implements ParentNode;
```

I think this means `query` and `queryAll` should work on the document fragment (which a shadow root is, no?).

**Comment by WebReflection** [comment]
so the version `1.4.4` I've just pushed pollutes, if necessary, `ShadowRoot` too but you have a point there, probably document fragment should be polluted as well.

**Comment by WebReflection** [comment]
OK, `1.4.5` has `query` and `queryAll` available for `DocumentFragment` too. Thanks for the report.

**Comment by cbas** [comment]
Thanks! :heart:

**Comment by cbas** [comment]
Will it be published to NPM? I'm seeing 1.4.1 as the latest release in the registry.

**Comment by WebReflection** [comment]
ooops, forgot that ... published now

**Comment by cbas** [comment]
Wow so fast :) Amazing!

On Thu, May 21, 2015 at 6:53 PM, Andrea Giammarchi <notifications@github.com
