### ISSUE TITLE
Anchor on the Web Page that the Elements#matches link on the readme is gone; temporary link to the MDN page about it reasonable?

### ISSUE THREAD

**Issue by lozandier** [WebReflection/dom4#17]
For whatever reason, The `#dom-element-matches` anchor is no longer available on [the page the current Element#Matches link references in the readme](http://www.w3.org/TR/dom/#dom-element-matches).  

This may give the impression to readers not keen on investigating more about the element that the  `Element#matches` method is deprecated despite the fact all major browsers support it except IE & at one point Opera didn't according to the [MDN Reference Page for the method](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches).

I also used Browserstack to see for myself (impressive work on this library, by the way) that still the case.

**Accordingly, the link to the MDN page perhaps may make sense to reference in the meantime until another, recent W3C document surfaces references it.

*Impressive* work on this library, by the way.

**Comment by WebReflection** [comment]
Thanks @lozandier 

There is [this alternative](http://www.w3.org/TR/selectors-api2/#matches) still as W3C standard, would it work?

**Comment by WebReflection** [comment]
actually [this one](https://dom.spec.whatwg.org/#dom-element-matches) seems more  appropriate,  for closest too. Will update

**Comment by lozandier** [comment]
No problem; I'm glad you found a better (more authoritative) reference.

On Wednesday, July 22, 2015, Andrea Giammarchi <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Closed #17 <https://github.com/WebReflection/dom4/issues/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebReflection/dom4/issues/17#event-361957634>.
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>
