### ISSUE TITLE
no polyfill for getElementsByClassName

### ISSUE THREAD

**Issue by t128** [WebReflection/dom4#21]
Hi,

there is no polyfill for the *getElementsByClassName* function.

http://www.w3.org/TR/dom/#dom-document-getelementsbyclassname

**Comment by WebReflection** [comment]
not sure it's worth implementing it since there is `queryAll('.class-name')` which is the most modern  way to go forward. `getElementsByClassName` is a very outdated method introduced in Firefox and adopted a bit too late as part of DOM4 specifications. `query` and `queryAll` ( read carefully, I didn't misspell `querySelector` ) are a modern alternative we should all use.

**Comment by aFarkas** [comment]
`getElementsByClassName` can't be polyfilled.

**Comment by WebReflection** [comment]
it probably could but at which cost in terms of size, tests, and performance, when we already have in the same spec better alternatives

**Comment by t128** [comment]
hmm, then we should state this in the README with a warning that this is not a "full" dom4 polyfill.

**Comment by t128** [comment]
@aFarkas 
```javascript
// untested pseudo code
Element.prototype.getElementsByClassName = function(search) {
  return this.queryAll(search.match(/\S+/g).map(c => `.${c}`).join(''));
};
```

**Comment by WebReflection** [comment]
> hmm, then we should state this in the README maybe with a warning that this is not a "full" dom4 polyfill.

it's already kinda stated at the bottom of the features https://github.com/WebReflection/dom4#features and all features are described.

Are you sure that will cover current specifications? And again, why even bothering when  we have `queryAll` ?

**Comment by WebReflection** [comment]
I'm asking 'cause if you are sure that's all it needs I wonder why you didn't just PR that.

In case you do, please add tests and for no reason use anything that needs a transpiler in a polyfill.

Assuming Array#map is there is ok but for performance sake I'd go for/i++ there. Cheers

**Comment by aFarkas** [comment]
@t128 
`getElementsByClassName` returns a node list. Which means it is not static, it is a live node list. Impossible, that you do this in IE8.

**Comment by WebReflection** [comment]
yeah, that was my understanding. So basically it acts like `getElementsByTagName` which involves the live behavior performance penalization  I was talking about.

Thanks for clarification, I won't waste time providing a broken poly then. Cheers

**Comment by t128** [comment]
ok, i don't need this (anymore). just switched to *query* & *queryAll* in my code.

**Comment by WebReflection** [comment]
you won't regret that choice ;-)

**Comment by t128** [comment]
> it's already kinda stated at the bottom of the features https://github.com/WebReflection/dom4#features and all features are described, meaning what's not described is probably not in ;-)

hmm, yeah and nooh, there is no paragraph "if u want getElementsByClassName then replace it with query or GTFO"

**Comment by t128** [comment]
@aFarkas 
https://developer.mozilla.org/en-US/docs/Web/API/NodeList#A_sometimes-live_collection

so getElementsByClassName should be a "static collection"?

**Comment by WebReflection** [comment]
bad attitude, I'll ignore it just once. You can PR and  point at this request where is explained why you should use `query` and `queryAll` instead.

Reagrds

**Comment by WebReflection** [comment]
> so getElementsByClassName should be a "static collection"?

I tell you already: **no** because there is no point, since `query` and `queryAll` are available, to bring an inconsistent broken old standard in here.

**Comment by t128** [comment]
also i can't find query/queryAll in the current version of the [dom4 draft](http://www.w3.org/TR/dom/). Any idea if it's in the standard now or no?

**Comment by WebReflection** [comment]
There is a link in the README which [brings you there](http://www.w3.org/TR/2015/WD-dom-20150428/#elements)

Since you didn't apparently notice it, I also would like to inform  you that as mentioned in the README [there are also alternatives](https://github.com/Raynos/DOM-shim) to this script.

DOM4 is pragmatic, you'll rarely find obsolete or useless old methods in here, just to give you a heads up of what this is, whish is not a full DOM4 polyfill

**Comment by t128** [comment]
> There is a link in the README which brings you there
yeah i know, but that's not the latest version, i think

**Comment by WebReflection** [comment]
I don't know what is that  link about and I am **very busy** 

Take care
