### ISSUE TITLE
Broken links in http://webreflection.github.io/dom4/

### ISSUE THREAD

**Issue by fvsch** [WebReflection/dom4#28]
(Thanks for the great polyfill :))

The following URLs are 404s:

- `test/dom4.js` -> http://webreflection.github.io/dom4/test/dom4.js
- `build/dom4.js` -> http://webreflection.github.io/dom4/build/dom4.js
- `build/dom4.max.js` -> http://webreflection.github.io/dom4/build/dom4.max.js

**Comment by WebReflection** [comment]
where are these broken links? Every link works in here to me:
https://github.com/WebReflection/dom4

which page are you looking at?

**Comment by fvsch** [comment]
I’m looking at http://webreflection.github.io/dom4/
Similarly for https://webreflection.github.io/dom4/

Since the `gh-pages` branch doesn’t have those files, the links end up not working.

**Comment by WebReflection** [comment]
I haven't updated that page in ages ... done now. You should probably always check the original README which is going to be surely updated.

Apologies for any inconvenient.
