### ISSUE TITLE
queryAll not in spec

### ISSUE THREAD

**Issue by sandstrom** [WebReflection/dom4#30]
It seems like queryAll has been removed from the spec. Perhaps a note could be added about that?
https://github.com/whatwg/dom/commit/10b6cf1ba02806220d5461a3bdb7939728b73635

More:
http://stackoverflow.com/a/38245620/118007

**Comment by WebReflection** [comment]
flagged as [DROPPED PROPOSAL](http://stackoverflow.com/questions/23269785/whats-the-difference-between-queryall-and-queryselectorall/38245620#38245620) in the README.md

Thanks
