### ISSUE TITLE
Page using dom4.max.js breaks in IE8 under certain circumstances

### ISSUE THREAD

**Issue by rylabo** [WebReflection/dom4#32]
Firstly thanks for the wonderful work on this. I find it difficult to believe someone would go to the trouble to ensure DOM4 support in IE8!

I've included the non-minified version ```dom4.max.js``` into my project, and under IE8, it broke at the line 819, saying ```expected identifier```. This was due to a trailing comma.

I've already cleaned up the problems, and added some jshint directives that lint based on Javascript 3, will follow up with a pull request.

**Comment by WebReflection** [comment]
So, basically you didn't use the uglified file which already solves the issue nobody had 'till today?

**Comment by rylabo** [comment]
Well, yes.

I'm using it as a dependency for another project, and rather than have several files load at once, I was going to concat all files and then uglify it into one bigger one...

**Comment by WebReflection** [comment]
It is, but it doesn't care about IE8.

It's an uplift task, I don't want anyone to file PRs compatible with IE8 here, I want people to contribute as freely as they want.

**Comment by rylabo** [comment]
I'm afraid I'm not sure what you are getting at by saying "contribute as freely as they want".

That said, I have closed the PR. Feel free to close this issue.

**Comment by WebReflection** [comment]
I don't want people to file PRs compatible with IE8.
I want people to fil PRs and let uglify produce the production version compatible with IE8.

You decided to rebundle this instead of using the CDN, you can instrument your tool chain to do whatever it wants without affecting a perfectly fine and easier to maintain ES5 code.
