### ISSUE TITLE
Remove non-standard `.query` and `.queryAll`

### ISSUE THREAD

**Issue by ryuran** [WebReflection/dom4#34]
This functions are not anymore in spec.
So a polyfill should not implement it in DOM.

**Comment by WebReflection** [comment]
it's [linked in the README](https://github.com/WebReflection/dom4#features), and [it has been already discussed](https://github.com/WebReflection/dom4/issues/31#issuecomment-272648118).

**Comment by WebReflection** [comment]
removed in v2
