### ISSUE TITLE
`char` is a reserved word

### ISSUE THREAD

**Issue by wodin** [WebReflection/dom4#35]
I'm trying to use blueprintjs from ClojureScript. blueprint has a dependency on dom4. When I try to compile the code, Google Closure Compiler processes all of the JavaScript code produced by the ClojureScript compiler and also the JavaScript dependencies, including dom4.

Google Closure Compiler complains that dom4 is using a reserved word as an identifier.

```
Oct 31, 2017 11:02:45 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /home/michael/work/personal/scratch/blueprint-test/public/js/release/node_modules/dom4/build/dom4.max.js:26: ERROR - Parse error. identifier is a reserved word
metaKey,altGraphKey);break;case 4:args.push(key,location,modifiers,repeat,locale);break;default:args.push(char,key,location,modifiers,repeat,locale)}out.initKeyboardEvent.apply(out,args)}else out.initEvent(type,bubbles,cancelable);for(key in out)if(defaults.hasOwnProperty(key)&&out[key]!==init[key])withInitValues(key,out,init);return out}KeyboardEvent.prototype=$KeyboardEvent.prototype;return KeyboardEvent}(window.KeyboardEvent||function KeyboardEvent(){});defineProperty(window,"KeyboardEvent",{value:o_O});
                                                                                                          ^

Oct 31, 2017 11:02:45 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_PARSE_ERROR. Parse error. identifier is a reserved word at /home/michael/work/personal/scratch/blueprint-test/public/js/release/node_modules/dom4/build/dom4.max.js line 26 : 106
```

Looking at the code, I suspect `char` was supposed to be `chr`:

https://github.com/WebReflection/dom4/blob/c26c850c9ccc6129600ea96c15a63834aae9d3f1/src/dom4.js#L643
...
https://github.com/WebReflection/dom4/blob/c26c850c9ccc6129600ea96c15a63834aae9d3f1/src/dom4.js#L682

**Comment by JakeChampion** [comment]
`char` is not a reserved word in the latest ecmascript 262 spec. Perhaps you are trying to compile down to ES3 or ES5?

**Comment by wodin** [comment]
Thanks, yes, I think the settings that were being used were causing Google Closure Compiler to treat the dom4 code as ES3.
