### ISSUE TITLE
DOM 3 polyfill

### ISSUE THREAD

**Issue by baptx** [WebReflection/dom4#38]
Will DOM3 polyfills eventually be added to this project or as a separate project? This would be a great alternative to jQuery, writing standard JavaScript supported everywhere without relying on a third-party library :)

**Comment by WebReflection** [comment]
ehr ... this project [covers all these browsers](https://github.com/WebReflection/dom4#compatibility)

down to IE8 via [this other project](https://github.com/WebReflection/ie8#ie8)

that means you can use up to DOM4 methods in every browser.

If you have any specific thing you think is from DOM 3 world and doesn't work somewhere, please let me know.

**Comment by baptx** [comment]
I was thinking of having a polyfill with all DOM3 functions, like jQuery but using standard JS.
Currently polyfills are separated in different projects like querySelector (added in IE8 https://github.com/mtsyganov/queryselector-polyfill) or MutationObserver (added in IE11 https://github.com/polymer/MutationObservers ).
For the MutationObserver polyfill, I just found that it has moved to a general polyfill: https://github.com/webcomponents/webcomponentsjs
How does webcomponentsjs compare to your project? You will stay focused on DOM4?

**Comment by WebReflection** [comment]
IMO webcomponentsjs went a bit too far with polyfills.

For custom elements, I personally use, and Google AMP uses, and Stencil JS uses, and AFrame VR also uses, [this polyfill](https://github.com/WebReflection/document-register-element) instead.

it's nearly 2018 and polyfills for `querySelector` seem to be slightly overrated ... only browsers not having it is IE < 8 and I don't think anyway has, or should be, interested in such case.

However, polyfill.io should cover your needs for jurassic stuff, targeting browsers via UA sniffing, although it apparently works well.

Have a look: https://polyfill.io/v2/docs/

AFAIK, Every other DOM 3 method works in every browser that is surfing the internet these days.

**Comment by baptx** [comment]
Thanks for the link. I don't care about older browsers since I use progressive enhancement but just wanted to know if it is exists.
