### ISSUE TITLE
Add support for :scope

### ISSUE THREAD

**Issue by oscarotero** [WebReflection/dom4#39]
Hi.
It would be awesome to include a shim for the scope pseudoelement. This allows to select direct children of an element. For example:

```js
ul.querySelectorAll(':scope > li:nth-child(odd)');
```

You can see an implementation here:

https://github.com/oscarotero/d.js/blob/master/d.js#L332

**Comment by WebReflection** [comment]
so few lines, yet so much room for improvements ... I'll consider this change, thanks for filing it

**Comment by WebReflection** [comment]
v2 is out with `:scope` support :tada:
