### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by Hypnosphi** [WebReflection/dom4#40]
It's quite hard to track what the changes are right now

**Comment by WebReflection** [comment]
it's both in the [readme](https://github.com/WebReflection/dom4#new-v2) and in [the only commit message](https://github.com/WebReflection/dom4/commit/01eba03b17fe28f331d4e0bbb6ee339a69db97ff) ?

**Comment by Hypnosphi** [comment]
Thanks. And `3.0.0` was just published by mistake, right?

**Comment by WebReflection** [comment]
yup ... I've messed up with `npm version major` ( twice in a row :sob: )

**Comment by WebReflection** [comment]
it should be delted now, v2 it is.
