### ISSUE TITLE
TypeError: Invalid calling object in EDGE or IE

### ISSUE THREAD

**Issue by huston007** [WebReflection/dom4#41]
In our app we use dom4 together with angular 1.6. It seems to be related, because dom4 fails when called from angular `jqLiteDealoc` function.

By debugging compiled code, I found out that the code below fails if called on DocumentFragment:

```
  what.querySelectorAll = function qSA(css) {
    var result = querySelectorAll.call(this, css);
    result.forEach = Array.prototype.forEach;
    return result
  }
```

<img width="660" alt="screen shot 2017-12-20 at 15 31 42" src="https://user-images.githubusercontent.com/4318513/34207340-18eb5adc-e59b-11e7-9127-182495cbd141.png">

The error itself looks like:
```
TypeError: Invalid calling object
   at qSA (eval code:702:11)
   at find (eval code:734:9)
   at qSA (eval code:727:9)
   at jqLiteDealoc (eval code:3252:5)
   at jqLiteEmpty (eval code:3452:3)
   at JQLite.prototype[name] (eval code:3724:9)
   at applyDirectivesToNode (eval code:9722:13)
   at compileNodes (eval code:9162:9)
   at compile (eval code:9043:7)
   at lazyCompilation (eval code:9490:11)
eval code (1881) (14794,9)
```

**Comment by bdwain** [comment]
I had this exact same error. Has anything been looked at yet as to why this is happening? I noticed that the call fails here

```js
      function find(node, method, css) {
        var oldID = node.id;
        var noParent = !node.parentNode;
        node.id = oldID || (prefix + counter++);
        if (noParent) parent.appendChild(node);
        var result = method.call(
          node.parentNode, //node.parentNode is invalid
          css.replace(
            /(^|,\s*)(:scope([ >]|$))?/g,
            function ($0, $1, $2, $3) {
              return $1 + '#' + node.id + ($3 || ' ');
            }
          )
        );
```

node.parentNode is a DocumentFragment, not a regular element, so it seems to fail there.

**Comment by WebReflection** [comment]
if anyone could give me a small use case that doesn't involve 3rd parts library and fails, I'd be happy to have a look

**Comment by WebReflection** [comment]
No answers in a while, and I think Angular 1 is death i the meanwhile, right? Closing this as there is nothing to do from my side.
