### ISSUE TITLE
TypeError in Opera Mobile 32

### ISSUE THREAD

**Issue by AlexWayfer** [WebReflection/dom4#45]
Catched in Sentry:

```
TypeError
object is not a function
/scripts/libs/dom4.js at line 2

/*! (C) Andrea Giammarchi - @WebReflection - Mit Style License */
(function(window){"use strict";function createDocumentFragment(){return document.createDocumentFragment()}function createElement(nodeName){r {snip}
```

User:

```
Opera Mobile 32.0.2254
Android 4.2.1
```

-----

Note about `r {snip}`: it's Sentry's artifact, in real-life there is:

```
/*! (C) Andrea Giammarchi - @WebReflection - Mit Style License */
(function(window){"use strict";function createDocumentFragment(){return document.createDocumentFragment()}function createElement(nodeName){return document.createElement(nodeName)}
```

**Comment by WebReflection** [comment]
it'd be awesome if you could use the `dom4.max.js` file instead so I understand which object is not actually a function.

I'm already happy it wasn't just `undefined is not a function` error 😄

**Comment by AlexWayfer** [comment]
> it'd be awesome if you could use the dom4.max.js file instead so I understand which object is not actually a function.

I was hoping you have a test environment.

I could not run a similar version of Opera neither in the emulator, nor at my smartphone.

OK, I'll switch to `dom4.max.js`. :disappointed:

**Comment by WebReflection** [comment]
> I was hoping you have a test environment.

I've tested manually [through this page](http://webreflection.github.io/dom4/test/) every device/browser in [the list](https://github.com/WebReflection/dom4#compatibility) but maybe I've missed Opera Mobile 32.0.2254 for Android 4.2.1 there 🤷‍♂️

**Comment by AlexWayfer** [comment]
> I could not run a similar version of Opera neither in the emulator, nor at my smartphone.

I ran it in the ARM (not x86) emulator. But I can't connect via `chrome://inspect/#devices`. But the site on which the error was occurred looks good.

>I've tested manually through this page every device/browser in the list but maybe I've missed Opera Mobile 32.0.2254 for Android 4.2.1 there :man_shrugging:

This page is green.

But user, triggered this error, is real, it's not a bot.

Let's wait for another event, but with `max` version. :man_shrugging:

**Comment by WebReflection** [comment]
> Let's wait for another event, but with max version. 🤷‍♂️

I guess that never happened. Closing.
