### ISSUE TITLE
Consider throwing for invalid names for toggleProperty

### ISSUE THREAD

**Issue by jonathanKingston** [WebReflection/dom4#47]
The standard for toggleAttribute throws an error for an invalid name. This wouldn't be true for the `hasAttribute->removeAttribute` code paths in the function implemented so I think this could be considered.
I was implementing this myself then was reminded to check here first :+1:.

My initial code was:
```
    function checkValidName(propertyName) {
        let first = /[:A-Z\_a-z\xc0-\xd6\xd8-\xf6\u00f8-\u02ff\x370-\x37d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\x3001-\xd7ff\xf900-\xfdcf\xfdf0-\xfffd\x10000-\xeffff]/;
        let second = /[\-\.0-9\xB7\u0300-\u036f\u203f-\u2040]/;
        let chars = [...propertyName];
        
        if (!first.test(chars.shift())) {
          return false;
        }
        for (let l of chars) {
           if (!first.test(l) && !second.test(l)) {
               return false;
           } 
        }
        return true;
    }
    Element.prototype.toggleAttribute = function (propertyName) {
      const charError = "InvalidCharacterError: String contains an invalid character";
      if (!checkValidValue(propertyName)) {
          throw new Error(charError);
      }
      ...
```

Likely something more readable than those RegEx lines could be done also :laughing:

**Comment by WebReflection** [comment]
That's interesting, but quite some code. I personally don't see any advantage in being defensive on a polyfill like this one, for the simple reason that you have already standard browsers throwing, and you test already in standard browsers, so that this code will effectively be never touched or useful in the real world.
