### ISSUE TITLE
append polyfill does not match the browser behavior 

### ISSUE THREAD

**Issue by stof** [WebReflection/dom4#50]
Tested both in Firefox 66 and Chromium 73

```
a = document.createElement('div')
a.append('foo', document.createElement('p'), 25)
console.log(a.childNodes)
```

Both browsers will add the `25` Number as a text node. The polyfill detects string with `typeof node === 'string'` to create a text node, which won't catch it.

**Comment by WebReflection** [comment]
Added test and fixed, thanks.
