### ISSUE TITLE
Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by piyushdp333** [WebReflection/dom4#52]
I have added <script
  src="http://cdnjs.cloudflare.com/ajax/libs/dom4/2.0.0/dom4.js"
></script> but still facing this error on IE 11. is there any solution available for that??

**Comment by WebReflection** [comment]
the [remove](https://github.com/WebReflection/dom4/blob/master/src/dom4.js#L216-L221) is there, but if you use it with some element that doesn't extend `Element` it won't work.

I am not sure they move `remove` and others to the `Node.prototype` though, so if that's the case, I might update the library, but basically it looks to me you are trying to remove non-elements.

**Comment by piyushdp333** [comment]
I have resolved this issue. apply polyfills for IE 11. 
reference: https://medium.com/agilix/internet-explorer-11-and-angular-2-50beda010aae
and did code changes:
 var blob = new Blob([csvArray]);
    if (window.navigator.msSaveOrOpenBlob) // IE hack; see http://msdn.microsoft.com/en-us/library/ie/hh779016.aspx
      window.navigator.msSaveBlob(blob, "ExportCSV.csv");
    else {
      var a = window.document.createElement("a");
      a.href = window.URL.createObjectURL(blob);
      a.download = "ExportCSV.csv";
      document.body.appendChild(a);
      a.click(); // IE: "Access is denied"; see: https://connect.microsoft.com/IE/feedback/details/797361/ie-10-treats-blob-url-as-cross-origin-and-denies-access
      document.body.removeChild(a);
after adding this..now i can export data in IE11

**Comment by WebReflection** [comment]
but this has nothing to do with remove, right? anyway, happy you solved.

**Comment by piyushdp333** [comment]
I think we can use removeChild(() method instead of remove()..
