### ISSUE TITLE
build / test setup

### ISSUE THREAD

**Issue by necolas** [WebReflection/dom4#7]
to work on this module involves reading through the Makefile and trying to work out which tasks you need to run in which order.

consider moving the npm dependencies into the 'devDependencies' field? or make some tasks dependencies of others, so running 'make test' or 'make build' works.

basically i don't really know how to run the tests. after running `make dependencies`, `make build` exits with errors and `make test` outputs nothing to the console.

**Comment by WebReflection** [comment]
hope it's OK if I close it since the described work around works fine here. Will put a reference to the README soon though.
