### ISSUE TITLE
node.replace(...nodes) fails when nodes contains node

### ISSUE THREAD

**Issue by hgl** [WebReflection/dom4#8]
Probably shouldn't use `replaceChild()` internally. Should follow the algorithm and use `insertBefore()` instead.

**Comment by hgl** [comment]
By failing, I mean `node` is gone after the replacement.

**Comment by hgl** [comment]
Also from the [discussion on whatwg mailing list](https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jan/0024.html), it's highly likely that `replace()` will be renamed to `replaceWith()`.

**Comment by WebReflection** [comment]
interesting gotcha. Do you have an example/test case? I am not sure a node can be already in the DOM **and** in a node that is not yet on the DOM. Unless this is a swap operation, and even `replaceChild` failed against this operation since quite ever. Thanks

**Comment by hgl** [comment]
Yep, it's a swap operation.

For example:
```
<div></div>
<div></div>
<div></div>
```
`node` is the first `div`, and `nodes` contains all `div`s. `node.replace(...nodes)` will result in `node` being removed from the DOM. `node.append(...nodes)` works fine.

**Comment by hgl** [comment]
Well, `replaceWith()` is [committed](https://github.com/whatwg/dom/commit/b7563aaf0864c8d104d18c36a9eda036c5205131). Not sure if you are interested to follow suit.

**Comment by WebReflection** [comment]
OK, I can add a `replaceWith` method but it's still not clear to me the example. Can you write anything that makes more sense like situation and expectations without using anything ES6 related as ..spread or stuff?

If you replace a node why would you expect this to be still there in the first place?

If you replace a node with a list of nodes + the node itself what would expect as final result?

Please help me figure out a work around for what I think might be a problem but I have no browser giving me a clue on how this is all handled. Thanks

**Comment by hgl** [comment]
> without using anything ES6 related as ..spread or stuff?

Why opposing es6? `...nodes` makes things easier to explain (instead of `node.replace.apply(node, nodes)`);

> If you replace a node why would you expect this to be still there in the first place?

My mental model for `node.replace(...nodes)` is that `node` is removed, and `nodes` is inserted at `node`'s original location. `node` still being in the DOM after the operation is a side effect of being contained in `nodes`.

> If you replace a node with a list of nodes + the node itself what would expect as final result?

nodes in `nodes` that exist before `node` are inserted before it, and after `node` are inserted after it.

> Please help me figure out a work around for ...

Actually the DOM spec already gives an algorithm: get `node`'s next sibling, remove `node`, and insert `nodes` before the next sibling.

I have sent a pull request to illustrate that.

**Comment by WebReflection** [comment]
ok, here is where it gets tricky ... first of all, I've asked about avoiding ES6 because I wasn't sure you were mentioning `...nodes` as the nodes container or a new list of nodes passed as arguments.

Now I understand what you mean ... and here comes the tricky part: I thought you were trying to substitute the node with its own container, and as soon as you **remove** the node you will remove it from its container too.

Now it's clean what you and specs meant so the fix is relatively trivial (nextSibling is not necessarily always there) so I might drop your PR since I had already one to push but wasn't 100% about expectations.

Cheers

**Comment by hgl** [comment]
Sorry for the confusion. I should be more careful when using the word "contain". :p

I believe you thought I was talking about `node.replace(nodeContainer)`? This should immediately result in a HierarchyRequestError, as required by the algorithm.

No worry about dropping my PR, thank you for implementing the fix.

**Comment by WebReflection** [comment]
just for record sake, your PR was breaking because if `nextSibling` is contained in the list of nodes to be replaced, `replaceChild` fails regardless. I am pushing now `1.2.1` with tests included and with `replaceWith` method in. Thanks again.

**Comment by hgl** [comment]
Well, after reading the spec again, I think I got the whole thing wrong. The current algorithm does require throwing an error if `node` is in `nodes`.

I made [a new post](https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0263.html) to the mailing list to discuss the edge case further.

**Comment by WebReflection** [comment]
so ... basically `.replace` is doing what `.replaceWith` is supposed to do and all I have to do is an alias instead ? Indeed I remember I followed specs for `.replace` and it was throwing as expected.

Please let me know so I can re-normalize this new method.

**Comment by hgl** [comment]
Yes, `replaceWith()` is just a rename of the original `replace()`, the algorithm was never changed in the spec.

However, looking at your implementation again, I think using `parentNode` saved before `mutationMacro()` has been executed is incorrect, because executing `mutationMacro()` can cause the context node being inserted into a doc frag, which changes its `parentNode`, when the context node is passed as one of the arguments. This affects `before()`, `after()` and `replaceWith()`.

For example, `before()` should be something like

```
      'before', function before() {
        var parentNode = this.parentNode;
        if (parentNode) {
          var node = mutationMacro(arguments);
          this.parentNode.insertBefore(node, this);
        }
      },
```

To let it fail when `node.before(node, anotherNode)` is executed.

I'm also trying to convince whatwg people to allow the context node being pass as one of the arguments to `replaceWith()`. Will let you know when they either reject or accept it.

**Comment by WebReflection** [comment]
I am not sure what you are saying ... the fragment is not returned as parent node once it's live on the DOM and the current algoritm was to not throw as you asked before.

Everything else is tested and validated against specs so I rather put replaceWith as replace and move on since AFAIK nobody ever had real problems in the real world with current specs.

**Comment by hgl** [comment]
> the fragment is not returned as parent node once it's live on the DOM

When you use `parentNode` in `parentNode.insertBefore` in the current implementation of `before()`, the fragment hasn't been inserted into the DOM yet. The spec requires you to use context node's **current** parentNode at that location, not the one before `mutationMacro()` is executed.

`node.before(node, anotherNode)` does fail in the current implementation, but fail for the wrong reason. Currently, it throws `NotFoundError`, the spec requires `HierarchyRequestError`.

But this is trivia, it's totally fine if you want to leave things the way they are.

Sorry for troubling you all this time, i should do more homework when opening an issue. The whole issue could just be requesting aliasing `replace()` to `replaceWith()`. :)

**Comment by WebReflection** [comment]
if you have a test for `.before` or there is a real issue with it (I need a fragment anyway if you pass more nodes) please file another bug, thanks.

Also please consider I am doing 99 things these days and making thrown errors perfect is not one of these ;-)
